# Generated by Django 5.1.1 on 2024-09-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Primary', 'Primary'), ('Middle School', 'Middle School'), ('High School', 'High School')], max_length=50)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarterly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annually_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
