# Generated by Django 5.1.1 on 2024-09-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='video_url',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.FileField(default='videos/default.mp4', upload_to='videos/'),
        ),
    ]
