# Generated by Django 5.1.1 on 2024-09-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_faqcategory_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('complaint_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
