# Generated by Django 5.1.1 on 2024-10-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
