# Generated by Django 5.1.2 on 2024-11-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('lawyer', 'Lawyer'), ('person', 'person')], default='regular', max_length=20),
        ),
    ]
